# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui4.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 826)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 0, 1061, 761))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.w3_2 = ImageView(self.layoutWidget_4)
        self.w3_2.setObjectName("w3_2")
        self.horizontalLayout_9.addWidget(self.w3_2)
        self.w4_2 = ImageView(self.layoutWidget_4)
        self.w4_2.setObjectName("w4_2")
        self.horizontalLayout_9.addWidget(self.w4_2)
        self.gridLayout_7.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4, 0, QtCore.Qt.AlignVCenter)
        self.b3_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.b3_2.setObjectName("b3_2")
        self.horizontalLayout_10.addWidget(self.b3_2)
        self.b4_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.b4_2.setObjectName("b4_2")
        self.horizontalLayout_10.addWidget(self.b4_2)
        self.gridLayout_7.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.tab.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 0, 1061, 761))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.w3 = ImageView(self.layoutWidget_3)
        self.w3.setObjectName("w3")
        self.horizontalLayout_7.addWidget(self.w3)
        self.w4 = ImageView(self.layoutWidget_3)
        self.w4.setObjectName("w4")
        self.horizontalLayout_7.addWidget(self.w4)
        self.gridLayout_6.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.layoutWidget_3)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2, 0, QtCore.Qt.AlignVCenter)
        self.b3 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.b3.setObjectName("b3")
        self.horizontalLayout_8.addWidget(self.b3)
        self.b4 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.b4.setObjectName("b4")
        self.horizontalLayout_8.addWidget(self.b4)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.tab.addTab(self.tab_3, "")
        self.gridLayout_4.addWidget(self.tab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.w3.ui.histogram.hide()
        self.w3.ui.roiBtn.hide()
        self.w3.ui.menuBtn.hide()
        self.w3.ui.roiPlot.hide()
        self.w4.ui.histogram.hide()
        self.w4.ui.roiBtn.hide()
        self.w4.ui.menuBtn.hide()
        self.w3_2.ui.histogram.hide()
        self.w3_2.ui.roiBtn.hide()
        self.w3_2.ui.menuBtn.hide()
        self.w4_2.ui.roiPlot.hide()
        self.w4_2.ui.histogram.hide()
        self.w4_2.ui.roiBtn.hide()
        self.w4_2.ui.menuBtn.hide()        
               
 
        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Matching Templates"))
        self.label_3.setText(_translate("MainWindow", "TIME"))
        self.b3_2.setText(_translate("MainWindow", "Import Image"))
        self.b4_2.setText(_translate("MainWindow", "Detect Faces"))
        self.tab.setTabText(self.tab.indexOf(self.tab_2), _translate("MainWindow", "Face Detection"))
        self.label.setText(_translate("MainWindow", "TIME"))
        self.b3.setText(_translate("MainWindow", "Import Image"))
        self.b4.setText(_translate("MainWindow", "Apply"))
        self.tab.setTabText(self.tab.indexOf(self.tab_3), _translate("MainWindow", "Face Recognition"))


from pyqtgraph import ImageView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
